export type BreedData = {
  breedName: string;
  category: 'Cattle' | 'Buffalo';
  purpose: 'Milk' | 'Draught' | 'Dual-Purpose';
  milkYield: number; // liters/day
  fatPercentage: number;
  strength: 'Low' | 'Medium' | 'High';
  feedRequirement: 'Low' | 'Medium' | 'High';
  maintenanceCost: 'Low' | 'Medium' | 'High';
  climateSuitability: ('Hot and Dry' | 'Hot and Humid' | 'Moderate' | 'Cold')[];
  diseaseResistance: 'Low' | 'Medium' | 'High';
  lifespan: number; // years
  careLevel: 'Low' | 'Medium' | 'High';
  marketPrice: number; // INR
  pros: string;
  cons: string;
};

export const indianBreedData: BreedData[] = [
  {
    breedName: 'Gir',
    category: 'Cattle',
    purpose: 'Milk',
    milkYield: 12,
    fatPercentage: 4.5,
    strength: 'Low',
    feedRequirement: 'Medium',
    maintenanceCost: 'Medium',
    climateSuitability: ['Hot and Dry', 'Hot and Humid'],
    diseaseResistance: 'High',
    lifespan: 15,
    careLevel: 'Medium',
    marketPrice: 80000,
    pros: 'High milk yield, good heat tolerance, and disease resistance. Milk has A2 protein.',
    cons: 'Late maturity, higher initial cost.',
  },
  {
    breedName: 'Sahiwal',
    category: 'Cattle',
    purpose: 'Milk',
    milkYield: 10,
    fatPercentage: 4.0,
    strength: 'Low',
    feedRequirement: 'Medium',
    maintenanceCost: 'Low',
    climateSuitability: ['Hot and Dry'],
    diseaseResistance: 'High',
    lifespan: 12,
    careLevel: 'Low',
    marketPrice: 65000,
    pros: 'Excellent disease resistance, heat tolerance, and ease of calving. Good for low-input systems.',
    cons: 'Lower milk yield compared to Gir, slow-moving.',
  },
  {
    breedName: 'Red Sindhi',
    category: 'Cattle',
    purpose: 'Milk',
    milkYield: 9,
    fatPercentage: 4.2,
    strength: 'Low',
    feedRequirement: 'Low',
    maintenanceCost: 'Low',
    climateSuitability: ['Hot and Dry', 'Hot and Humid'],
    diseaseResistance: 'Medium',
    lifespan: 14,
    careLevel: 'Low',
    marketPrice: 55000,
    pros: 'High heat tolerance, good for crossbreeding, efficient milk producer on low feed.',
    cons: 'Smaller in size, lower peak milk yield.',
  },
  {
    breedName: 'Hallikar',
    category: 'Cattle',
    purpose: 'Draught',
    milkYield: 2,
    fatPercentage: 3.0,
    strength: 'High',
    feedRequirement: 'Medium',
    maintenanceCost: 'Low',
    climateSuitability: ['Hot and Dry', 'Moderate'],
    diseaseResistance: 'High',
    lifespan: 18,
    careLevel: 'Low',
    marketPrice: 45000,
    pros: 'Excellent draught animals, known for their speed and endurance. Very hardy.',
    cons: 'Very low milk yield, can be aggressive.',
  },
  {
    breedName: 'Khillar',
    category: 'Cattle',
    purpose: 'Draught',
    milkYield: 1.5,
    fatPercentage: 3.2,
    strength: 'High',
    feedRequirement: 'Medium',
    maintenanceCost: 'Low',
    climateSuitability: ['Hot and Dry'],
    diseaseResistance: 'High',
    lifespan: 16,
    careLevel: 'Low',
    marketPrice: 50000,
    pros: 'Extremely powerful and fast, ideal for heavy farm work and transport in arid regions.',
    cons: 'Almost no milk production, requires experienced handling.',
  },
  {
    breedName: 'Kankrej',
    category: 'Cattle',
    purpose: 'Dual-Purpose',
    milkYield: 6,
    fatPercentage: 4.0,
    strength: 'Medium',
    feedRequirement: 'Medium',
    maintenanceCost: 'Medium',
    climateSuitability: ['Hot and Dry'],
    diseaseResistance: 'High',
    lifespan: 15,
    careLevel: 'Medium',
    marketPrice: 60000,
    pros: 'Good balance of milk production and draught power. Hardy and adaptable.',
    cons: 'Not specialized for either milk or draught, moderate in both aspects.',
  },
  {
    breedName: 'Tharparkar',
    category: 'Cattle',
    purpose: 'Dual-Purpose',
    milkYield: 7,
    fatPercentage: 4.8,
    strength: 'Medium',
    feedRequirement: 'Low',
    maintenanceCost: 'Low',
    climateSuitability: ['Hot and Dry'],
    diseaseResistance: 'High',
    lifespan: 16,
    careLevel: 'Low',
    marketPrice: 70000,
    pros: 'Excellent heat and drought tolerance. Good milk yield with high fat content for a dual breed.',
    cons: 'Slower growth rate compared to specialized breeds.',
  },
  {
    breedName: 'Murrah',
    category: 'Buffalo',
    purpose: 'Milk',
    milkYield: 14,
    fatPercentage: 7.0,
    strength: 'Low',
    feedRequirement: 'High',
    maintenanceCost: 'High',
    climateSuitability: ['Moderate', 'Hot and Humid'],
    diseaseResistance: 'Medium',
    lifespan: 12,
    careLevel: 'High',
    marketPrice: 120000,
    pros: 'One of the highest milk-yielding buffalo breeds globally. Milk has very high fat content.',
    cons: 'Requires significant feed and care, high initial investment, sensitive to extreme heat without water access.',
  },
  {
    breedName: 'Nili-Ravi',
    category: 'Buffalo',
    purpose: 'Milk',
    milkYield: 12,
    fatPercentage: 6.5,
    strength: 'Low',
    feedRequirement: 'High',
    maintenanceCost: 'Medium',
    climateSuitability: ['Moderate', 'Cold'],
    diseaseResistance: 'Medium',
    lifespan: 13,
    careLevel: 'Medium',
    marketPrice: 100000,
    pros: 'High milk yield, distinctive white markings. Adaptable to colder climates better than other buffalo.',
    cons: 'Slightly lower milk yield and fat % than Murrah. Requires good quality fodder.',
  },
];
